[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.curl", "php82Extensions.zip", "php82Extensions.pdo_mysql", "composer"]

[phases.build]
cmds = ["cd finr-api && composer install --no-dev --optimize-autoloader"]

[start]
cmd = "cd finr-api && php artisan serve --host=0.0.0.0 --port=$PORT"
